services:
  frontend:
    build:
      context: ./../../fullstack-todo-list/Frontend
      dockerfile: Dockerfile.frontend
    container_name: todo-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./../../fullstack-todo-list/Backend
      dockerfile: Dockerfile.backend
    container_name: todo-backend
    ports:
      - "3000:3000"
    # environment:
    #   MONGO_URI: mongodb+srv://username:password@cluster.mongodb.net/yourDatabaseName?retryWrites=true&w=majority
#   database:
#     image: mongo:latest
#     container_name: todo-mongodb
#     restart: on-failure
#     ports:
#       - "27017:27017"
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: example
#       MONGO_INITDB_DATABASE: todo_db
#     volumes:
#       - mongo-data:/data/db

# volumes:
#   mongo-data:
